// Generated by CoffeeScript 1.11.1

/*
System.Core.Client.commandFetch
 */
var fetchCommand;

fetchCommand = function(address, args) {
  var ajax;
  ajax = new XMLHttpRequest();
  ajax.onreadystatechange = function() {
    var x;
    if (this.readyState === 4 && this.status === 200) {
      x = this.responseText;
      return document.sysConsole.print(x);
    }
  };
  ajax.open("GET", address + '?' + args, true);
  return ajax.send();
};
