// Generated by CoffeeScript 1.11.1

/*
System.Core.Client.ioLoader
require(System.Core.io)
require(System.Core.commandLoader)
 */
var inputOutput, testIO;

inputOutput = function(console) {
  return console.onInputChange(function() {
    return console.print(loadCommand(console.readLine()));
  });
};

testIO = function(console) {
  return console.onInputChange(function() {
    return console.print(console.readLine());
  });
};

document.addEventListener("DOMContentLoaded", function() {
  var myconsole;
  myconsole = new consoleIO("consoleIn", "consoleOut", "outCanvas");
  document.sysConsole = myconsole;
  return inputOutput(myconsole);
});
