// Generated by CoffeeScript 1.11.1

/*
System.Kernel.login
 */
var login, processLogin;

processLogin = function() {
  if (document.getElementById("loginIn").value === "hero24") {
    document.cookie = "Auth=1";
    return location.reload(true);
  }
};

login = function() {
  var input, section, submit;
  section = document.createElement("section");
  section.setAttribute("id", "loginBox");
  input = document.createElement("input");
  input.setAttribute("id", "loginIn");
  submit = document.createElement("button");
  submit.setAttribute("id", "loginSubmit");
  submit.innerHTML = "Login";
  section.appendChild(input);
  section.appendChild(submit);
  document.body.appendChild(section);
  return submit.addEventListener("click", processLogin, false);
};

document.addEventListener("DOMContentLoaded", login, false);
