// Generated by CoffeeScript 1.11.1

/*
System.Core.io
 */
var consoleIO;

consoleIO = (function() {
  function consoleIO(inID, outID, outCanvasID) {
    this.consoleIn = document.getElementById(inID);
    this.consoleOut = document.getElementById(outID);
    this.outCanvas = document.getElementById(outCanvasID);
  }

  consoleIO.prototype.readLine = function() {
    var val;
    val = this.consoleIn.value;
    this.consoleIn.value = "";
    return val;
  };

  consoleIO.prototype.onInputChange = function(onChangeFunction) {
    return this.consoleIn.onchange = onChangeFunction;
  };

  consoleIO.prototype.print = function(output) {
    var newOut, outID;
    this.consoleOut.innerHTML = output;
    outID = this.consoleOut.id;
    this.consoleOut.removeAttribute("id");
    this.consoleOut.setAttribute("class", "pastOutput");
    newOut = document.createElement("p");
    newOut.id = outID;
    this.outCanvas.appendChild(newOut);
    this.consoleOut = document.getElementById(outID);
    return window.scrollBy(0, 1000);
  };

  return consoleIO;

})();
